// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC16NyDMdOIaLGRu9yshdSMlWm_wO8kgQk',
    appId: '1:441697192983:web:e44b9a992a29fe060e6052',
    messagingSenderId: '441697192983',
    projectId: 'words-pzl-001',
    authDomain: 'words-pzl-001.firebaseapp.com',
    storageBucket: 'words-pzl-001.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBgay4oRAX07gXv1V4zfc8WngLzTjiAq0',
    appId: '1:441697192983:android:a0358eecc64ac2330e6052',
    messagingSenderId: '441697192983',
    projectId: 'words-pzl-001',
    storageBucket: 'words-pzl-001.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASSSRjr19L6kYHqRq8yVgi6UmVZWcrFgs',
    appId: '1:441697192983:ios:c3c46dce7b3e26b90e6052',
    messagingSenderId: '441697192983',
    projectId: 'words-pzl-001',
    storageBucket: 'words-pzl-001.firebasestorage.app',
    iosBundleId: 'com.puzzle.wordPuzzle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASSSRjr19L6kYHqRq8yVgi6UmVZWcrFgs',
    appId: '1:441697192983:ios:c3c46dce7b3e26b90e6052',
    messagingSenderId: '441697192983',
    projectId: 'words-pzl-001',
    storageBucket: 'words-pzl-001.firebasestorage.app',
    iosBundleId: 'com.puzzle.wordPuzzle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC16NyDMdOIaLGRu9yshdSMlWm_wO8kgQk',
    appId: '1:441697192983:web:6abf21d3adb94b510e6052',
    messagingSenderId: '441697192983',
    projectId: 'words-pzl-001',
    authDomain: 'words-pzl-001.firebaseapp.com',
    storageBucket: 'words-pzl-001.firebasestorage.app',
  );
}
